### ISSUE TITLE
Allow to define environment variable for logging container

### ISSUE THREAD

**Issue by renaudhager** [shopware/shopware-operator#75]
### Improvement

Hi,

It would be very useful to set dedicated environment variables for the logging container for the store deployment and for the different jobs (setup and migration).
Right now it works for logging container for the Shopware deployment (Storefront/admin/worker) but not for the Setup or MigrationJob.

### Reason

That will for instance allows to set dedicated labels for Fluent-bit and made logging more efficient

### Information

I tried the following:

Not working:
```
store:
  setupJobContainer:
    extraContainers:
      - name: logging
        env:
        - name: FLUENT_BIT_LABELS
          value: "job=fluentbit,service=setupJob"
  migrationJobContainer:
    extraContainers:
      - name: logging
        env:
        - name: FLUENT_BIT_LABELS
          value: "job=fluentbit,service=migrationJob"
```
This works for the Shopware deployment:
```
container:
   ...
    extraEnvs:
      - name: FLUENT_BIT_LABELS
        value: "job=fluentbit,service=shopwareCore"
```

### Definition of Done

Having a desired environment variable for the logging container in the setup and migration job pod.
