### ISSUE TITLE
Add configuration for SwagAnalytics app

### ISSUE THREAD

**Issue by TrayserCassa** [shopware/shopware-operator#81]
### Improvement

We need to set the analytics app configuration in the operator to disable or enable the analytics app.

### Reason

Since we are the hoster of the db and also the hoster of the analytic db, we are not allowed to gather this data. 

### Information

https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Resources/config/packages/shopware.yaml#L547

Current structure, might be changed
```
shopware:
  usage_data:
    collection_enabled: false # <-- will be new
    gateway:
      dispatch_enabled: false # <-- exists since 6.5.7.0
```

### Definition of Done

- Overwrite the configuration in the operator
- Add it to the helm-chart and disable it for PaaS
